project:
  type: book
  output-dir: ../docs

book:
  title: "DataSHIELD Workshop"
  author: 
    - Juan R. González
    - David Sarrat González
  repo-url: https://github.com/isglobal-brge/workshop_ICO
  repo-actions: [issue]
  sharing: [twitter, linkedin]
  favicon: favicon.ico
  chapters:
    - index.qmd
    - chapters/datashield.Rmd
    - chapters/dsomop.Rmd
  sidebar:
    logo: logo.svg

format:
  html:
    theme: cosmo
    number-sections: false
    css: ../docs/custom.css
    execute:
      warning: false
      message: false
      error: false