---
title: "Workshop Introduction"
author: 
  - "Juan R González"
  - "David Sarrat González"
---

# Introduction

This website hosts the materials and exercises for the DataSHIELD workshop at the Institut Català d'Oncologia (ICO). 

On it you will find reading materials, setup tutorials, workshop indications and practical exercises.

## Getting Started

All practical exercises will be conducted using the [public Opal demo server](https://opal-demo.obiba.org/). This server provides a fully functional DataSHIELD environment with sample datasets that workshop participants can use to replicate the examples.

Login credentials for the demo server are:

- Username: `dsuser`
- Password: `P@ssw0rd`

## Prerequisites

Before starting, make sure to install the required R packages in your local machine:

```{r eval=FALSE}
install.packages('DSI')
install.packages('DSOpal')
install.packages('dsBaseClient', repos=c(getOption('repos'), 'http://cran.datashield.org'), dependencies=TRUE)
install.packages('metafor')
devtools::install_github('lifecycle-project/ds-helper')
devtools::install_github('isglobal-brge/dsOMOPClient')
devtools::install_github('isglobal-brge/dsOMOPHelper')
```

## Slides

You can find the slides used in the workshop in the following links:

- [DataSHIELD slides](https://raw.githubusercontent.com/isglobal-brge/workshop_ICO/main/slides/datashield_slides.pdf)
- [dsOMOP slides](https://raw.githubusercontent.com/isglobal-brge/workshop_ICO/main/slides/dsomop_slides.pdf)

## Complementary materials

- [DataSHIELD Beginner's Tutorial](https://data2knowledge.atlassian.net/wiki/spaces/DSDEV/pages/931069953/Beginners+Tutorial+DataSHIELD+v6.1)
- [Resource bookdown: Examples of resources](https://isglobal-brge.github.io/resource_bookdown/resourcer.html#examples-of-resources)
- [OHDSI Book chapter 'The Common Data Model'](https://ohdsi.github.io/TheBookOfOhdsi/CommonDataModel.html)
- [OHDSI Book chapter 'Standardized Vocabularies'](https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html)
- [dsOMOP website](https://isglobal-brge.github.io/dsOMOP/)
- [Using tidyverse within DataSHIELD](https://cran.r-project.org/web/packages/dsTidyverseClient/vignettes/dstidyverse.html)

## Exercises solutions

- [DataSHIELD exercises solutions](https://raw.githubusercontent.com/isglobal-brge/workshop_ICO/refs/heads/main/solutions/datashield_solutions.R)

## Schedule

| Time          | Topic                                          |
|---------------|------------------------------------------------|
| 09:00         | Welcome                                        |
| 09:15 - 09:45 | Introduction to DataSHIELD and OPAL            |
| 09:45 - 11:00 | Workshop DataSHIELD data analysis + exercise   |
| 11:00 - 11:30 | Break                                          |
| 11:30 - 12:00 | Introduction to OMOP and dsOMOP and extensions |
| 12:00 - 12:30 | Workshop dsOMOP dataset creation + analysis    |

## Credits

Material developed at the Bioinformatics Research Group in Epidemiology (BRGE) of the Barcelona Institute for Global Health (ISGlobal) by Juan R González and David Sarrat González.
